web:
    endpoint: 'https://www.anxietycanada.com?%s'
    prefix: 'imper'
    alphabet: 'abcdefghijklmnopqrstuvwxyz'
    secretlength: 8
    alignmentalphabet: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    recordscardinality: 1
    method: 'serial'
    samplesize: 1
    confidence_threshold: 1.0
